# -*- coding: utf-8 -*-
"""bert_sentiment_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRfr1GWhM0CkHKCrT5sz1W65g07xSZu0
"""

import torch
import torch.nn as nn
from transformers import BertModel

class BertClassifier(nn.Module):
    def __init__(self, num_classes):
        super(BertClassifier, self).__init__()
        self.bert_model = BertModel.from_pretrained("bert-base-multilingual-uncased")
        self.dropout = nn.Dropout(0.3)
        self.classifier = nn.Linear(self.bert_model.config.hidden_size, num_classes)

    def forward(self, input_ids, attention_mask):
        bert_output = self.bert_model(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = bert_output[1]
        output = self.dropout(pooled_output)
        logits = self.classifier(output)
        return logits